### ISSUE TITLE
implement a better version of toggleCombat if possible

### ISSUE THREAD

**Issue by Osmosis-Wrench** [Osmosis-Wrench/ODefeat#7]
currently uses a tcai to disable ai for all npc, would rather a mass calm spell if possible. investigate how feasible that would be, should be doable.

**Comment by kannonfodder** [comment]
If an AOE calm doesnt work , could just loop through all actors locally and apply a beefed up Calm spell (default one only goes to level 9)

**Comment by Sairion350** [comment]
👍
